version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cloud-access-mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-cloudaccess123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-cloud_access}
    volumes:
      - mongodb_data_prod:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb.conf:/etc/mongod.conf:ro
    command: mongod --config /etc/mongod.conf
    networks:
      - cloud-access-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: cloud-access-backend-prod
    restart: always
    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME:-cloud_access}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENVIRONMENT=production
      - DEBUG=false
    depends_on:
      - mongodb
    networks:
      - cloud-access-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    container_name: cloud-access-frontend-prod
    restart: always
    depends_on:
      - backend
    networks:
      - cloud-access-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: cloud-access-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - cloud-access-network-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data_prod:
    driver: local
  nginx_logs:
    driver: local

networks:
  cloud-access-network-prod:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16